<template>
  <div class="wrapper">
    <div class="section header-filter" :style="headerStyle">
      <div class="container">
        <div class="md-layout">
          <div class="__div md-layout-item md-size-100">
            <p class="title md-display-2 text-esc-darkgrey">
                <strong>Terms and Condition</strong>
            </p>
          </div>
          <div class="__div md-layout-item md-size-100 md-layout md-gutter md-alignment-center-space-between">
              <p class="__title md-layout-item md-size-100">
                  General Terms
              </p>
              <p class="__content md-layout-item md-size-100">
                  By accessing the website, you confirm that you are in agreement with and bound by the terms of service contained in the <em>Terms & Conditions</em> outlined below. These terms apply to the entire website and any email or other type of communication between you and under no circumstances shall the team be liable for any direct, indirect, special, incidental or consequential damages, including, but not limited to, loss of data or profit, arising out of the use, or the inability to use, the materials on this site, even if team or an authorized representative has been advised of the possibility of such damages. If your use of materials from this site results in the need for servicing, repair or correction of equipment or data, you assume any costs thereof.ESCORD will not be responsible for any outcome that may occur during the course of usage of our resources We reserve the rights to change prices and revise the resources usage policy in any moment.
              </p>
          </div>
          <div class="__div md-layout-item md-size-100 md-layout md-gutter md-alignment-center-space-between">
              <p class="__title md-layout-item md-size-100">
                  License
              </p>
              <p class="__content md-layout-item md-size-100">
                  ESCORD grants you a revocable, non-exclusive, non-transferable, limited license to download, install and use our service strictly in accordance with the terms of this Agreement.
                </p> 
                  <br>
                <p class="__content md-layout-item md-size-100">
                  These Terms & Conditions are a contract between you and ESCORD (referred to in these Terms & Conditions as "<em>ESCORD</em>", "<em>us</em>", "<em>we</em>" or "<em>our</em>"), the provider of the ESCORD website and the services accessible from the ESCORD website (which are collectively referred to in these Terms & Conditions as the "<em>ESCORD Service</em>").
                </p>
                  <br>
                <p class="__content md-layout-item md-size-100">
                  You are agreeing to be bound by these Terms & Conditions. If you do not agree to these Terms & Conditions, please do not use the Service. In these Terms & Conditions, "you" refers both to you as an individual and to the entity you represent. If you violate any of these Terms & Conditions, we reserve the right to cancel your account or block access to your account without notice.
              </p>
          </div>
          <div class="__div md-layout-item md-size-100 md-layout md-gutter md-alignment-center-space-between">
              <p class="__title md-layout-item md-size-100">
                  Definitions and key terms
              </p>
              <p class="__content md-layout-item md-size-100">
                  For this Terms & Conditions:
                  <ul>
                      <li>
                          Cookie: small amount of
data generated by a website and saved by your web browser. It is used to identify your browser, provide analytics, remember information about you such as your language preference or login information. 
                      </li>
                      <li>
                          Company: when this policy mentions "Company,” “we,” "us,” or “our,” it refers to ESCORD that is responsible for your information under
this Privacy Policy. 
                      </li>
                      <li>
                          Country: where ESCORD or the owners/founders of ESCORD are based, in this case is PHILIPPINES. 
                      </li>
                      <li>
                          Customer: refers to the company, organization or person that signs up to use the ESCORD Service to manage the relationships with your consumers or
service users.v
                      </li>
                      <li>
                          Device: any internet
connected device such as a phone, tablet, computer or any other device that can be used to visit ESCORD and use the services. 
                      </li>
                      <li>
                          IP address: Every device connected to the Internet is assigned a number known as an Internet protocol (IP) address. These numbers are usually assigned in geographic blocks. An IP address can often be used to identify the location from which a device is connecting
to the Internet. 
                      </li>
                      <li>
                          Personnel: refers to those individuals who are employed by ESCORD or are under contract to perform a service on behalf of one of the parties.
                      </li>
                      <li>
                          Personal Data: any information that directly, indirectly, or in connection with other information – including a personal identification number – allows for the identification or identifiability of a natural
person.
                      </li>
                      <li>
                          Service: refers to the service
provided by ESCORD as described in the relative terms (if available) and on
this platform.
                      </li>
                      <li>
                          Third-party service: refers to
advertisers, contest sponsors, promotional and marketing partners, and others who provide our content or whose products or services we think may
interest you. 
                      </li>
                      <li>
                          Website: ESCORD's site, which can be accessed via this URL: https://front
srms.vercel.app/#/. 
                      </li>
                      <li>
                          You: a person or entity that is
registered with ESCORD to use the Services.
                      </li>
                  </ul>
              </p>
          </div>
          <div class="__div md-layout-item md-size-100 md-layout md-gutter md-alignment-center-space-between">
              <p class="__title md-layout-item md-size-100">
                  Restrictions
              </p>
              <p class="__content md-layout-item md-size-100">
                  You agree not to, and you will not permit others to:
• License, sell, rent, lease,
assign, distribute, transmit, host, outsource, disclose or otherwise commercially exploit the service or make the platform available

              </p>
          </div>
          <div class="__div md-layout-item md-size-100 md-layout md-gutter md-alignment-center-space-between">
              <p class="__title md-layout-item md-size-100">
                  Your Suggestions
              </p>
              <p class="__content md-layout-item md-size-100">
                  Any feedback, comments, ideas, improvements or suggestions (collectively, "Suggestions") provided by you to us with respect to the service shall remain the sole and exclusive property of us. We shall be free to use, copy, modify, publish, or redistribute the Suggestions for any purpose and in any way without any credit or any compensation to you.

              </p>
          </div>
          <div class="__div md-layout-item md-size-100 md-layout md-gutter md-alignment-center-space-between">
              <p class="__title md-layout-item md-size-100">
                  Your Consent
              </p>
              <p class="__content md-layout-item md-size-100">
                  We've updated our Terms & Conditions to provide you with complete transparency into what is being set when you visit our site and how it's being used. By using our service, you hereby consent to our 

Terms & Conditions.
              </p>
          </div>
          <div class="__div md-layout-item md-size-100 md-layout md-gutter md-alignment-center-space-between">
              <p class="__title md-layout-item md-size-100">
                  Links to Other Websites
              </p>
              <p class="__content md-layout-item md-size-100">
                  Our service may contain links to other websites that are not operated by Us. If you click on a third party link, You will be directed to that third party's site. We strongly advise You to review the Terms & Conditions of every site You visit. We have no control over and assume no responsibility for the content, Terms & Conditions or practices of any third party sites or services.

              </p>
          </div>
          <div class="__div md-layout-item md-size-100 md-layout md-gutter md-alignment-center-space-between">
              <p class="__title md-layout-item md-size-100">
                  Cookies
              </p>
              <p class="__content md-layout-item md-size-100">
                  We use "Cookies" to identify the areas of our website that you have visited. A Cookie is a small piece of data stored on your computer or mobile device by your web browser. We use cookies to enhance the performance and functionality of our service but are non-essential to their use. However, without these cookies, certain functionality like videos may become unavailable or you would be required to enter your login details every time you visit our platform as we would not be able to remember that you had logged in previously. Most web browsers can be set to disable the use of cookies. However, if you disable Cookies, you may not be able to access functionality on our website correctly or at all. We never place Personally Identifiable Information in Cookies.

              </p>
          </div>
          <div class="__div md-layout-item md-size-100 md-layout md-gutter md-alignment-center-space-between">
              <p class="__title md-layout-item md-size-100">
                  Changes To Our Terms & Conditions
              </p>
              <p class="__content md-layout-item md-size-100">
                  You acknowledge and agree that we may stop (permanently or temporarily) providing the Service (or any features within the Service) to you or to users generally at our sole discretion, without prior notice to you. You may stop using the Service at any time. You do not need to specifically inform us when you stop using the Service. You acknowledge and agree that if we disable access to your account, you may be prevented from accessing the Service, your account details or any files or other materials which is contained in your account. If we decide to change our Terms & Conditions, we will post those changes on this page, and/or update the Terms & Conditions modification date below.

              </p>
          </div>
          <div class="__div md-layout-item md-size-100 md-layout md-gutter md-alignment-center-space-between">
              <p class="__title md-layout-item md-size-100">
                  Modifications to Our service
              </p>
              <p class="__content md-layout-item md-size-100">
                  We reserve the right to modify, suspend or discontinue, temporarily or permanently, the service or any service to which it connects, with or without notice and without liability to you.
              </p>
          </div>
          <div class="__div md-layout-item md-size-100 md-layout md-gutter md-alignment-center-space-between">
              <p class="__title md-layout-item md-size-100">
                  Updates to Our service
              </p>
              <p class="__content md-layout-item md-size-100">
                  We may from time to time provide enhancements or improvements to the features/ functionality of the service, which may include patches, bug fixes, updates, upgrades and other modifications ("Updates"). Updates may modify or delete certain features and/or functionalities of the service. You agree that we have no obligation to (i) provide any Updates, or (ii) continue to provide or enable any particular features and/or functionalities of the service to you. You further agree that all Updates will be (i) deemed to constitute an integral part of the service, and (ii) subject to the terms and conditions of this Agreement.
              </p>
          </div>
          <div class="__div md-layout-item md-size-100 md-layout md-gutter md-alignment-center-space-between">
              <p class="__title md-layout-item md-size-100">
                  Third-Party Services
              </p>
              <p class="__content md-layout-item md-size-100">
                  We may display, include or make available third-party content (including data, information, applications and other products services) or provide links to thirdparty websites or services ("ThirdParty Services"). You acknowledge and agree that we shall not be responsible for any Third-Party Services, including their accuracy, completeness, timeliness, validity, copyright compliance, legality, decency, quality or any other aspect thereof. We do not assume and shall not have any liability or responsibility to you or any other person or entity for any Third-Party Services. Third-Party Services and links thereto are provided solely as a convenience to you and you access and use them entirely at your own risk and subject to such third parties' terms and conditions.
              </p>
          </div>
          <div class="__div md-layout-item md-size-100 md-layout md-gutter md-alignment-center-space-between">
              <p class="__title md-layout-item md-size-100">
                  Term and Termination
              </p>
              <p class="__content md-layout-item md-size-100">
                  This Agreement shall remain in effect until terminated by you or us. We may, in its sole discretion, at any time and for any or no reason, suspend or terminate this Agreement with or without prior notice. This Agreement will terminate immediately, without prior notice from us, in the event that you fail to comply with any provision of this Agreement. You may also terminate this Agreement by deleting the service and all copies thereof from your computer. Upon termination of this Agreement, you shall cease all use of the service and delete all copies of the service from your computer. Termination of this Agreement will not limit any of our rights or remedies at law or in equity in case of breach by you (during the term of this Agreement) of any of your obligations under the present Agreement.
              </p>
          </div>
          <!-- <div class="__div md-layout-item md-size-100 md-layout md-gutter md-alignment-center-space-between">
              <p class="__title md-layout-item md-size-100">
                  Term and Termination
              </p>
              <p class="__content md-layout-item md-size-100">
                  If you are a copyright owner or such owner's agent and believe any material from us constitutes an infringement on your copyright, please contact us setting forth the following information: (a) a physical or electronic signature of the copyright owner or a person authorized to act on his behalf; (b) identification of the material that is claimed to be infringing; (c) your contact information, including your address, telephone number, and an email; (d) a statement by you that you have a good faith belief that use of the material is not authorized by the copyright owners; and (e) the a statement that the information in the notification is accurate, and, under penalty of perjury you are authorized to act on behalf of the
owner.

              </p>
          </div> -->
          <div class="__div md-layout-item md-size-100 md-layout md-gutter md-alignment-center-space-between">
              <p class="__title md-layout-item md-size-100">
                  No Warranties
              </p>
              <p class="__content md-layout-item md-size-100">
                  The service is provided to you "AS IS" and "AS AVAILABLE" and with all faults and defects without warranty of any kind. To the maximum extent permitted under applicable law, we, on our own behalf and on behalf of our affiliates and our respective licensors and service providers, expressly disclaims all warranties, whether express, implied, statutory or otherwise, with respect to the service, including all implied warranties of merchantability, fitness for a particular purpose, title and non-infringement, and warranties that may arise out of course of dealing, course of performance, usage or trade practice. Without limitation to the foregoing, we provide no warranty or undertaking, and makes no representation of any kind that the service will meet your requirements, achieve any intended results, be compatible or work with any other software, websites, systems or services, operate without interruption, meet any performance or reliability standards or be error free or that any errors or defects can or will be corrected.
Without limiting the foregoing, neither us nor any provider makes any representation or warranty of any kind, express or implied: (i) as to the operation or availability of the service, or the information, content, and materials or products included thereon; (ii) that the service will be uninterrupted or error-free; (iii) as to the accuracy, reliability, or currency of any information or content provided through the service; or (iv) that the service, its servers, the content, or e-mails sent from or on behalf of us are free of viruses, scripts, trojan horses, worms, malware, timebombs or other harmful components. Some jurisdictions do not allow the exclusion of or limitations on implied warranties or the limitations on the applicable statutory rights of a consumer, so some or all of the above exclusions and limitations may not apply to you.

              </p>
          </div>
          <div class="__div md-layout-item md-size-100 md-layout md-gutter md-alignment-center-space-between">
              <p class="__title md-layout-item md-size-100">
                  Severability
              </p>
              <p class="__content md-layout-item md-size-100">
                  If any provision of this Agreement is held to be unenforceable or invalid, such provision will be changed and interpreted to accomplish the objectives of such provision to the greatest extent possible under applicable law and the remaining provisions will continue in full force and effect.

              </p>
          </div>
          <div class="__div md-layout-item md-size-100 md-layout md-gutter md-alignment-center-space-between">
              <p class="__title md-layout-item md-size-100">
                  Entire Agreement
              </p>
              <p class="__content md-layout-item md-size-100">
                  The Agreement constitutes the entire agreement between you and us regarding your use of the service and supersedes all prior and contemporaneous written or oral agreements between you and us. You may be subject to additional terms and conditions that apply when you use or purchase other services from us, which we will provide to you at the time of such use or purchase.
              </p>
          </div>
          <div class="__div md-layout-item md-size-100 md-layout md-gutter md-alignment-center-space-between">
              <p class="__title md-layout-item md-size-100">
                  Updates to Our Terms
              </p>
              <p class="__content md-layout-item md-size-100">
                  We may change our Service and policies, and we may need to make changes to these Terms so that they accurately reflect our Service and policies. Unless otherwise required by law, we will notify you (for example, through our Service) before we make changes to these Terms and give you an opportunity to review them before they go into effect. Then, if you continue to use the Service, you will be bound by the updated Terms. If you do not want to agree to these or any updated Terms, you can delete your account.
              </p>
          </div>
          <div class="__div md-layout-item md-size-100 md-layout md-gutter md-alignment-center-space-between">
              <p class="__title md-layout-item md-size-100">
                  Intellectual Property
              </p>
              <p class="__content md-layout-item md-size-100">
                  Our platform and its entire contents, features and functionality (including but not limited to all information, software, text, displays, images, video and audio, and the design, selection and arrangement thereof), are owned by us, its licensors or other providers of such material and are protected by and international copyright, trademark, patent, trade secret and other intellectual property or proprietary rights laws. The material may not be copied, modified, reproduced, downloaded or distributed in any way, in whole or in part, without the express prior written permission of us, unless and except as is expressly provided in these Terms & Conditions. Any unauthorized use of the material is prohibited.
              </p>
          </div>
          <div class="__div md-layout-item md-size-100 md-layout md-gutter md-alignment-center-space-between">
              <p class="__title md-layout-item md-size-100">
                  Disclaimer
              </p>
              <p class="__content md-layout-item md-size-100">
                  We are not responsible for any content, code or any other imprecision. We do not provide warranties or guarantees. In no event shall we be liable for any special, direct, indirect, consequential, or incidental damages or any damages whatsoever, whether in an action of contract, negligence or other tort, arising out of or in connection with the use of the Service or the contents of the Service. We reserve the right to make additions, deletions, or modifications to the contents on the Service at any time without prior notice.
Our Service and its contents are provided "as is" and "as available" without any warranty or representations of any kind, whether express or implied. We are a distributor and not a publisher of the content supplied by third parties; as such, our exercises no editorial control over such content and makes no warranty or representation as to the accuracy, reliability or currency of any information, content, service or merchandise provided through or accessible via our Service. Without limiting the foregoing, We specifically disclaim all warranties and representations in any content transmitted on or in connection with our Service or on sites that may appear as links on our Service, or in the products provided as a part of, or otherwise in connection with, our Service, including without limitation any warranties of merchantability, fitness for a particular purpose or noninfringement of third party rights. No oral advice or written information given by us or any of its affiliates, employees, officers, directors, agents, or the like will create a warranty. Price and availability information is subject to change without notice. Without limiting the foregoing, we do not warrant that our Service will be uninterrupted, uncorrupted, timely, or error-free.

              </p>
          </div>
          <div class="__div md-layout-item md-size-100 md-layout md-gutter md-alignment-center-space-between">
              <p class="__title md-layout-item md-size-100">
                  Contact Us
              </p>
              <p class="__content md-layout-item md-size-100">
                  Don't hesitate to contact us if you have any questions.
                  <ul>
                      <li>
                          Via this Link: https://front-srms.vercel.app/#/ or</li>
                        <li>
                            Email us at: ucc.escord@gmail.com
                        </li>
                  </ul>
              </p>
          </div>
        </div>
      </div>
    </div>
    <vue-headful title="Terms and Condition | ESCORD"/>
  </div>
</template>

<script>
export default {
  bodyClass: "escord-contact-us-page",
  computed: {
    headerStyle() {
      return {
        backgroundImage: `url(${this.header})`
      };
    }
  },
};
</script>

<style lang="scss" scoped>
.__div {
    margin: 0.85em 0 1.2em 0 !important;
}

.__title {
    font-size: 1.35em !important;
    letter-spacing: 0.15em !important;
    text-transform: uppercase !important;
    font-weight: 700 !important;
    margin-bottom: 0.3em !important;
}

.__content {
    padding-left: 3.15em !important;
    font-weight: 400 !important;
    font-size: 1em !important;
    text-align: justify !important;
}
</style>
